language: node_js
node_js:
  - 5.9.1
services: mongodb
before_deploy:
  - bash ./deploy.sh
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: QXpsJC2gdJ5ajcdC2C/sujRG3SkBzk+Acuki38csDZa9xKmCbblH+Oz6OSWtLQzZUxhs3fZ/k6I+KTqD8ACLkXnroMe/ysEAIEkUvDl6YcN61QdxcYCAgfk4L7HF4Z6urw6LFdjyFxmJSsVWCyEX/Cd/AlHJbclLQxe1ihMlkXt/qD4d8yw2KIAl7WemF07G3P9whZm+NTMIiDQEPLh5boEIt3mSWOyRBb0vYY4PTcQxGwndsrPQXZbPeb+QUHFgIvUcf/A1Wk0oemjsKX28F48x8E2kvsIVDqJ6ut4NvHVa9xtrG1L8fAVgsAcpBjBOBcqq9u/ISLaU+0ogHbvXeMWfTRsurQLc11SJel0OuA9QZJ0mMH1OpO5u6WnrP+tKDIESjeYQKP9JT6yOPRn0Df8JXWRHQAPiuG9mIUcapIA3p0JR2wEbjmjSnkU0ud6V+01QVn+MhZHt579CRVhb7zIgK3hDva/jT07an5BgaPDfwEb9B6kAxGisvAkyeuoM1tpFcsJ2Fu5VJA8ljuPxr6JYvQsEy4fvfesaqCvAxy/vzo9ZqzT8WLn/9qQso7yORU6DAokHqm6qMewuUtSmyUNourvqXigWUn4ADuG26gzUHAL6oZSdVmc+crggxZKCVQbVqxyxMsRcwaWCurjgdCP/W4soaZ2ineI4oRrlTrM=
  app: vast-garden-11249
  strategy: git
after_deploy:
  - bash ./after_deploy.sh